# Generated by Django 4.0.4 on 2023-05-07 04:09

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0004_auto_20200425_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementimages',
            name='cover',
            field=stdimage.models.JPEGField(force_min_size=False, upload_to='images/', variations={'custom': {'crop': True, 'height': 750, 'width': 550}}),
        ),
    ]
