# Generated by Django 4.0.4 on 2023-05-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0005_alter_elementimages_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='price',
            field=models.IntegerField(),
        ),
    ]
